datos_estados = {
    "2019": [
        {
            "Entidad": "Aguascalientes",
            "Denuncias": "40",
            "Investigaciones": "2",
            "Carpetas": "40",
            "Imputaciones": "8",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "1",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "8%",
            "Archivos": "5",
            "NoAcciónPenal": "13",
            "Abstenciones": "1",
            "TotalNoCombate": "48%",
            "Presupuesto": "1,767,612.00",
            "Montos": "2,168,539.00"
        },
        {
            "Entidad": "Baja California",
            "Denuncias": "0",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Baja California Sur",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Campeche",
            "Denuncias": "217",
            "Investigaciones": "217",
            "Carpetas": "217",
            "Imputaciones": "1",
            "Vinculaciones": "1",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "217",
            "NoAcciónPenal": "12",
            "Abstenciones": "2",
            "TotalNoCombate": "106%",
            "Presupuesto": "1,094,437.00",
            "Montos": "0.00"
        },
        {
            "Entidad": "Chiapas",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Chihuahua",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Ciudad de México",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Coahuila",
            "Denuncias": "117",
            "Investigaciones": "30",
            "Carpetas": "117",
            "Imputaciones": "16",
            "Vinculaciones": "15",
            "Sentencias": "0",
            "Judicialización": "16",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "3",
            "TotalCambate": "16%",
            "Archivos": "0",
            "NoAcciónPenal": "6",
            "Abstenciones": "0",
            "TotalNoCombate": "5%",
            "Presupuesto": "51,219,068.00",
            "Montos": "700,000.00"
        },
        {
            "Entidad": "Colima",
            "Denuncias": "252",
            "Investigaciones": "0",
            "Carpetas": "252",
            "Imputaciones": "4",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "4",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "1",
            "Reparaciónes": "4",
            "TotalCambate": "5%",
            "Archivos": "14",
            "NoAcciónPenal": "14",
            "Abstenciones": "9",
            "TotalNoCombate": "15%",
            "Presupuesto": "10,992,300.00",
            "Montos": "0.00"
        },
        {
            "Entidad": "Durango",
            "Denuncias": "71",
            "Investigaciones": "0",
            "Carpetas": "71",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "0",
            "TotalNoCombate": "0%",
            "Presupuesto": "19,103,000.00",
            "Montos": "0.00"
        },
        {
            "Entidad": "Federal",
            "Denuncias": "932",
            "Investigaciones": "0",
            "Carpetas": "773",
            "Imputaciones": "6",
            "Vinculaciones": "6",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "0",
            "TotalNoCombate": "0%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Guanajuato",
            "Denuncias": "50",
            "Investigaciones": "50",
            "Carpetas": "50",
            "Imputaciones": "8",
            "Vinculaciones": "2",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "2",
            "Reparaciónes": "1",
            "TotalCambate": "16%",
            "Archivos": "2",
            "NoAcciónPenal": "25",
            "Abstenciones": "1",
            "TotalNoCombate": "56%",
            "Presupuesto": "13,292,802.52",
            "Montos": "601,269.00"
        },
        {
            "Entidad": "Guerrero",
            "Denuncias": "24",
            "Investigaciones": "24",
            "Carpetas": "24",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "0",
            "NoAcciónPenal": "5",
            "Abstenciones": "0",
            "TotalNoCombate": "21%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Hidalgo",
            "Denuncias": "320",
            "Investigaciones": "320",
            "Carpetas": "106",
            "Imputaciones": "12",
            "Vinculaciones": "12",
            "Sentencias": "2",
            "Judicialización": "7",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "4",
            "Procedimiento": "1",
            "Reparaciónes": "0",
            "TotalCambate": "11%",
            "Archivos": "1",
            "NoAcciónPenal": "80",
            "Abstenciones": "0",
            "TotalNoCombate": "76%",
            "Presupuesto": "13,921,754.00",
            "Montos": "2,950,000.00"
        },
        {
            "Entidad": "Jalisco",
            "Denuncias": "976",
            "Investigaciones": "NR",
            "Carpetas": "976",
            "Imputaciones": "12",
            "Vinculaciones": "12",
            "Sentencias": "0",
            "Judicialización": "22",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "5",
            "TotalCambate": "3%",
            "Archivos": "208",
            "NoAcciónPenal": "9",
            "Abstenciones": "64",
            "TotalNoCombate": "29%",
            "Presupuesto": "63,584,466.00",
            "Montos": "0.00"
        },
        {
            "Entidad": "México",
            "Denuncias": "4287",
            "Investigaciones": "4620",
            "Carpetas": "4287",
            "Imputaciones": "444",
            "Vinculaciones": "127",
            "Sentencias": "23",
            "Judicialización": "444",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "11",
            "Reparaciónes": "0",
            "TotalCambate": "11%",
            "Archivos": "2671",
            "NoAcciónPenal": "0",
            "Abstenciones": "295",
            "TotalNoCombate": "69%",
            "Presupuesto": "240,745,697.00",
            "Montos": "NR"
        },
        {
            "Entidad": "Michoacán",
            "Denuncias": "71",
            "Investigaciones": "71",
            "Carpetas": "71",
            "Imputaciones": "9",
            "Vinculaciones": "7",
            "Sentencias": "6",
            "Judicialización": "9",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "1",
            "Reparaciónes": "1",
            "TotalCambate": "17%",
            "Archivos": "10",
            "NoAcciónPenal": "21",
            "Abstenciones": "3",
            "TotalNoCombate": "48%",
            "Presupuesto": "4,562,742.00",
            "Montos": "0.00"
        },
        {
            "Entidad": "Morelos",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nayarit",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nuevo León",
            "Denuncias": "40",
            "Investigaciones": "4",
            "Carpetas": "39",
            "Imputaciones": "3",
            "Vinculaciones": "2",
            "Sentencias": "2",
            "Judicialización": "3",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "10%",
            "Archivos": "9",
            "NoAcciónPenal": "6",
            "Abstenciones": "1",
            "TotalNoCombate": "41%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Oaxaca",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR.00"
        },
        {
            "Entidad": "Puebla",
            "Denuncias": "758",
            "Investigaciones": "0",
            "Carpetas": "776",
            "Imputaciones": "10",
            "Vinculaciones": "9",
            "Sentencias": "0",
            "Judicialización": "25",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "1",
            "Reparaciónes": "0",
            "TotalCambate": "4%",
            "Archivos": "9",
            "NoAcciónPenal": "761",
            "Abstenciones": "7",
            "TotalNoCombate": "100%",
            "Presupuesto": "20,303,078.19",
            "Montos": "0.00"
        },
        {
            "Entidad": "Querétaro",
            "Denuncias": "57",
            "Investigaciones": "0",
            "Carpetas": "57",
            "Imputaciones": "18",
            "Vinculaciones": "21",
            "Sentencias": "4",
            "Judicialización": "11",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "11",
            "Procedimiento": "4",
            "Reparaciónes": "1",
            "TotalCambate": "47%",
            "Archivos": "1",
            "NoAcciónPenal": "19",
            "Abstenciones": "7",
            "TotalNoCombate": "47%",
            "Presupuesto": "13,626,194.03",
            "Montos": "0.00"
        },
        {
            "Entidad": "Quintana Roo",
            "Denuncias": "450",
            "Investigaciones": "54",
            "Carpetas": "450",
            "Imputaciones": "35",
            "Vinculaciones": "23",
            "Sentencias": "5",
            "Judicialización": "43",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "6",
            "Procedimiento": "3",
            "Reparaciónes": "1",
            "TotalCambate": "12%",
            "Archivos": "0",
            "NoAcciónPenal": "127",
            "Abstenciones": "3",
            "TotalNoCombate": "29%",
            "Presupuesto": "44,502,135.00",
            "Montos": "216,880,480.94"
        },
        {
            "Entidad": "San Luis Potosí",
            "Denuncias": "264",
            "Investigaciones": "0",
            "Carpetas": "88",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "16",
            "NoAcciónPenal": "29",
            "Abstenciones": "6",
            "TotalNoCombate": "58%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Sinaloa",
            "Denuncias": "10",
            "Investigaciones": "0",
            "Carpetas": "5",
            "Imputaciones": "1",
            "Vinculaciones": "1",
            "Sentencias": "1",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "20%",
            "Archivos": "6",
            "NoAcciónPenal": "5",
            "Abstenciones": "0",
            "TotalNoCombate": "220%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Sonora",
            "Denuncias": "237",
            "Investigaciones": "0",
            "Carpetas": "234",
            "Imputaciones": "12",
            "Vinculaciones": "12",
            "Sentencias": "4",
            "Judicialización": "14",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "7%",
            "Archivos": "8",
            "NoAcciónPenal": "91",
            "Abstenciones": "1",
            "TotalNoCombate": "43%",
            "Presupuesto": "57,941,693.00",
            "Montos": "81,012.22"
        },
        {
            "Entidad": "Tabasco",
            "Denuncias": "46",
            "Investigaciones": "0",
            "Carpetas": "46",
            "Imputaciones": "11",
            "Vinculaciones": "11",
            "Sentencias": "5",
            "Judicialización": "6",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "5",
            "Reparaciónes": "5",
            "TotalCambate": "39%",
            "Archivos": "1",
            "NoAcciónPenal": "0",
            "Abstenciones": "10",
            "TotalNoCombate": "24%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Tamaulipas",
            "Denuncias": "372",
            "Investigaciones": "0",
            "Carpetas": "372",
            "Imputaciones": "24",
            "Vinculaciones": "23",
            "Sentencias": "4",
            "Judicialización": "15",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "4",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "5%",
            "Archivos": "1",
            "NoAcciónPenal": "172",
            "Abstenciones": "29",
            "TotalNoCombate": "54%",
            "Presupuesto": "1,856,157.93",
            "Montos": "0.00"
        },
        {
            "Entidad": "Tlaxcala",
            "Denuncias": "400",
            "Investigaciones": "400",
            "Carpetas": "400",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "0",
            "TotalNoCombate": "0%",
            "Presupuesto": "8,205,784.34",
            "Montos": "0.00"
        },
        {
            "Entidad": "Veracruz",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Yucatán",
            "Denuncias": "178",
            "Investigaciones": "1",
            "Carpetas": "149",
            "Imputaciones": "3",
            "Vinculaciones": "4",
            "Sentencias": "0",
            "Judicialización": "4",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "3",
            "TotalCambate": "5%",
            "Archivos": "4",
            "NoAcciónPenal": "14",
            "Abstenciones": "1",
            "TotalNoCombate": "13%",
            "Presupuesto": "NR",
            "Montos": "0.00"
        },
        {
            "Entidad": "Zacatecas",
            "Denuncias": "315",
            "Investigaciones": "0",
            "Carpetas": "315",
            "Imputaciones": "4",
            "Vinculaciones": "1",
            "Sentencias": "1",
            "Judicialización": "34",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "8",
            "Procedimiento": "1",
            "Reparaciónes": "6",
            "TotalCambate": "16%",
            "Archivos": "127",
            "NoAcciónPenal": "0",
            "Abstenciones": "74",
            "TotalNoCombate": "64%",
            "Presupuesto": "4,425,217.37",
            "Montos": "0.00"
        }
    ],
    "2020": [
        {
            "Entidad": "Aguascalientes",
            "Denuncias": "39",
            "Investigaciones": "0",
            "Carpetas": "39",
            "Imputaciones": "3",
            "Vinculaciones": "3",
            "Sentencias": "1",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "5%",
            "Archivos": "3",
            "NoAcciónPenal": "8",
            "Abstenciones": "1",
            "TotalNoCombate": "31%",
            "Presupuesto": "$7,506,000.00",
            "Montos": "$103,500.00"
        },
        {
            "Entidad": "Baja California",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Baja California Sur",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Campeche",
            "Denuncias": "124",
            "Investigaciones": "124",
            "Carpetas": "124",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "7",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "6%",
            "Archivos": "41",
            "NoAcciónPenal": "2",
            "Abstenciones": "4",
            "TotalNoCombate": "38%",
            "Presupuesto": "$11,364,105.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Chiapas",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Chihuahua",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Ciudad de México",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Coahuila",
            "Denuncias": "35",
            "Investigaciones": "7",
            "Carpetas": "35",
            "Imputaciones": "15",
            "Vinculaciones": "15",
            "Sentencias": "0",
            "Judicialización": "15",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "57%",
            "Archivos": "0",
            "NoAcciónPenal": "39",
            "Abstenciones": "0",
            "TotalNoCombate": "111%",
            "Presupuesto": "$47,615,147.37 ",
            "Montos": "$1,906,970.09 "
        },
        {
            "Entidad": "Colima",
            "Denuncias": "253",
            "Investigaciones": "0",
            "Carpetas": "253",
            "Imputaciones": "3",
            "Vinculaciones": "2",
            "Sentencias": "1",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "3",
            "TotalCambate": "2%",
            "Archivos": "3",
            "NoAcciónPenal": "3",
            "Abstenciones": "8",
            "TotalNoCombate": "6%",
            "Presupuesto": "$3,648,442.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Durango",
            "Denuncias": "154",
            "Investigaciones": "0",
            "Carpetas": "154",
            "Imputaciones": "20",
            "Vinculaciones": "9",
            "Sentencias": "0",
            "Judicialización": "20",
            "Criterio": "0",
            "Controversias": "3",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "15%",
            "Archivos": "0",
            "NoAcciónPenal": "9",
            "Abstenciones": "3",
            "TotalNoCombate": "8%",
            "Presupuesto": "$22,727,278.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Federal",
            "Denuncias": "1468",
            "Investigaciones": "0",
            "Carpetas": "1567",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "19",
            "Criterio": "1",
            "Controversias": "8",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "2%",
            "Archivos": "0",
            "NoAcciónPenal": "169",
            "Abstenciones": "33",
            "TotalNoCombate": "13%",
            "Presupuesto": "$110,000,000.00",
            "Montos": "NR"
        },
        {
            "Entidad": "Guanajuato",
            "Denuncias": "64",
            "Investigaciones": "64",
            "Carpetas": "64",
            "Imputaciones": "2",
            "Vinculaciones": "2",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "2",
            "Reparaciónes": "1",
            "TotalCambate": "13%",
            "Archivos": "2",
            "NoAcciónPenal": "25",
            "Abstenciones": "1",
            "TotalNoCombate": "44%",
            "Presupuesto": "$13,292,802.52 ",
            "Montos": "$22,205.00"
        },
        {
            "Entidad": "Guerrero",
            "Denuncias": "29",
            "Investigaciones": "29",
            "Carpetas": "29",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "1",
            "NoAcciónPenal": "2",
            "Abstenciones": "0",
            "TotalNoCombate": "10%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Hidalgo",
            "Denuncias": "325",
            "Investigaciones": "325",
            "Carpetas": "179",
            "Imputaciones": "14",
            "Vinculaciones": "11",
            "Sentencias": "14",
            "Judicialización": "5",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "6%",
            "Archivos": "0",
            "NoAcciónPenal": "107",
            "Abstenciones": "0",
            "TotalNoCombate": "60%",
            "Presupuesto": "$10,475,959.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Jalisco",
            "Denuncias": "798",
            "Investigaciones": "NR",
            "Carpetas": "798",
            "Imputaciones": "10",
            "Vinculaciones": "10",
            "Sentencias": "1",
            "Judicialización": "68",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "7",
            "Procedimiento": "1",
            "Reparaciónes": "8",
            "TotalCambate": "11%",
            "Archivos": "107",
            "NoAcciónPenal": "10",
            "Abstenciones": "408",
            "TotalNoCombate": "66%",
            "Presupuesto": "$66,220,466.00",
            "Montos": "$-"
        },
        {
            "Entidad": "México",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "",
            "Presupuesto": "$273,447,994.20",
            "Montos": "NR"
        },
        {
            "Entidad": "Michoacán",
            "Denuncias": "119",
            "Investigaciones": "119",
            "Carpetas": "119",
            "Imputaciones": "9",
            "Vinculaciones": "5",
            "Sentencias": "0",
            "Judicialización": "4",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "5%",
            "Archivos": "7",
            "NoAcciónPenal": "25",
            "Abstenciones": "4",
            "TotalNoCombate": "30%",
            "Presupuesto": "$8,600,773.00",
            "Montos": "$4,748.14 "
        },
        {
            "Entidad": "Morelos",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nayarit",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nuevo León",
            "Denuncias": "72",
            "Investigaciones": "3",
            "Carpetas": "594",
            "Imputaciones": "9",
            "Vinculaciones": "3",
            "Sentencias": "1",
            "Judicialización": "9",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "NR",
            "TotalCambate": "2%",
            "Archivos": "312",
            "NoAcciónPenal": "7",
            "Abstenciones": "3",
            "TotalNoCombate": "54%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Oaxaca",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Puebla",
            "Denuncias": "517",
            "Investigaciones": "1",
            "Carpetas": "1050",
            "Imputaciones": "33",
            "Vinculaciones": "29",
            "Sentencias": "4",
            "Judicialización": "39",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "4%",
            "Archivos": "0",
            "NoAcciónPenal": "618",
            "Abstenciones": "0",
            "TotalNoCombate": "59%",
            "Presupuesto": "$29,959,794.65 ",
            "Montos": "$-"
        },
        {
            "Entidad": "Querétaro",
            "Denuncias": "50",
            "Investigaciones": "NR",
            "Carpetas": "50",
            "Imputaciones": "14",
            "Vinculaciones": "28",
            "Sentencias": "7",
            "Judicialización": "10",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "6",
            "Procedimiento": "7",
            "Reparaciónes": "1",
            "TotalCambate": "48%",
            "Archivos": "0",
            "NoAcciónPenal": "12",
            "Abstenciones": "0",
            "TotalNoCombate": "24%",
            "Presupuesto": "$15,944,242.60",
            "Montos": "$-"
        },
        {
            "Entidad": "Quintana Roo",
            "Denuncias": "480",
            "Investigaciones": "31",
            "Carpetas": "480",
            "Imputaciones": "57",
            "Vinculaciones": "53",
            "Sentencias": "2",
            "Judicialización": "41",
            "Criterio": "5",
            "Controversias": "32",
            "Suspensiónes": "27",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "22%",
            "Archivos": "0",
            "NoAcciónPenal": "63",
            "Abstenciones": "0",
            "TotalNoCombate": "13%",
            "Presupuesto": "$44,502,135.00",
            "Montos": "$31,627,428.11 "
        },
        {
            "Entidad": "San Luis Potosí",
            "Denuncias": "59",
            "Investigaciones": "0",
            "Carpetas": "59",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "5%",
            "Archivos": "9",
            "NoAcciónPenal": "22",
            "Abstenciones": "6",
            "TotalNoCombate": "63%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Sinaloa",
            "Denuncias": "11",
            "Investigaciones": "1",
            "Carpetas": "13",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "1",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "8%",
            "Archivos": "1",
            "NoAcciónPenal": "0",
            "Abstenciones": "4",
            "TotalNoCombate": "38%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Sonora",
            "Denuncias": "95",
            "Investigaciones": "0",
            "Carpetas": "89",
            "Imputaciones": "14",
            "Vinculaciones": "14",
            "Sentencias": "1",
            "Judicialización": "11",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "12%",
            "Archivos": "5",
            "NoAcciónPenal": "27",
            "Abstenciones": "1",
            "TotalNoCombate": "37%",
            "Presupuesto": "$69,242,502.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Tabasco",
            "Denuncias": "59",
            "Investigaciones": "0",
            "Carpetas": "59",
            "Imputaciones": "13",
            "Vinculaciones": "13",
            "Sentencias": "9",
            "Judicialización": "11",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "9",
            "Reparaciónes": "8",
            "TotalCambate": "49%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "1",
            "TotalNoCombate": "2%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Tamaulipas",
            "Denuncias": "242",
            "Investigaciones": "0",
            "Carpetas": "242",
            "Imputaciones": "11",
            "Vinculaciones": "11",
            "Sentencias": "0",
            "Judicialización": "18",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "6",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "10%",
            "Archivos": "2",
            "NoAcciónPenal": "68",
            "Abstenciones": "18",
            "TotalNoCombate": "36%",
            "Presupuesto": "$2,777,455.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Tlaxcala",
            "Denuncias": "261",
            "Investigaciones": "261",
            "Carpetas": "261",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "5",
            "NoAcciónPenal": "16",
            "Abstenciones": "0",
            "TotalNoCombate": "8%",
            "Presupuesto": "$10,441,710.43 ",
            "Montos": "$-"
        },
        {
            "Entidad": "Veracruz",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Yucatán",
            "Denuncias": "76",
            "Investigaciones": "0",
            "Carpetas": "51",
            "Imputaciones": "11",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "3",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "2",
            "TotalCambate": "16%",
            "Archivos": "15",
            "NoAcciónPenal": "14",
            "Abstenciones": "0",
            "TotalNoCombate": "57%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Zacatecas",
            "Denuncias": "341",
            "Investigaciones": "0",
            "Carpetas": "341",
            "Imputaciones": "15",
            "Vinculaciones": "1",
            "Sentencias": "1",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "115",
            "NoAcciónPenal": "0",
            "Abstenciones": "68",
            "TotalNoCombate": "54%",
            "Presupuesto": "$7,502,893.49 ",
            "Montos": "$-"
        }
    ],
    "2021": [
        {
            "Entidad": "Aguascalientes",
            "Denuncias": "38",
            "Investigaciones": "0",
            "Carpetas": "38",
            "Imputaciones": "7",
            "Vinculaciones": "8",
            "Sentencias": "1",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "3%",
            "Archivos": "1",
            "NoAcciónPenal": "2",
            "Abstenciones": "0",
            "TotalNoCombate": "8%",
            "Presupuesto": "$7,506,000.00",
            "Montos": "$19,594,630.43 "
        },
        {
            "Entidad": "Baja California",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Baja California Sur",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Campeche",
            "Denuncias": "187",
            "Investigaciones": "187",
            "Carpetas": "187",
            "Imputaciones": "10",
            "Vinculaciones": "9",
            "Sentencias": "0",
            "Judicialización": "22",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "15%",
            "Archivos": "24",
            "NoAcciónPenal": "12",
            "Abstenciones": "5",
            "TotalNoCombate": "22%",
            "Presupuesto": "$10,959,518.00",
            "Montos": "$580,000.00"
        },
        {
            "Entidad": "Chiapas",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Chihuahua",
            "Denuncias": "166",
            "Investigaciones": "0",
            "Carpetas": "19",
            "Imputaciones": "8",
            "Vinculaciones": "5",
            "Sentencias": "3",
            "Judicialización": "8",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "3",
            "Reparaciónes": "0",
            "TotalCambate": "63%",
            "Archivos": "0",
            "NoAcciónPenal": "13",
            "Abstenciones": "1",
            "TotalNoCombate": "74%",
            "Presupuesto": "$54,863,400.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Ciudad de México",
            "Denuncias": "255",
            "Investigaciones": "255",
            "Carpetas": "255",
            "Imputaciones": "13",
            "Vinculaciones": "20",
            "Sentencias": "NR",
            "Judicialización": "8",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "3",
            "Reparaciónes": "0",
            "TotalCambate": "5%",
            "Archivos": "0",
            "NoAcciónPenal": "13",
            "Abstenciones": "1",
            "TotalNoCombate": "5%",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Coahuila",
            "Denuncias": "55",
            "Investigaciones": "3",
            "Carpetas": "55",
            "Imputaciones": "8",
            "Vinculaciones": "8",
            "Sentencias": "0",
            "Judicialización": "15",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "36%",
            "Archivos": "0",
            "NoAcciónPenal": "39",
            "Abstenciones": "0",
            "TotalNoCombate": "71%",
            "Presupuesto": "$28,222,873.56 ",
            "Montos": "$5,545,185.87 "
        },
        {
            "Entidad": "Colima",
            "Denuncias": "347",
            "Investigaciones": "0",
            "Carpetas": "347",
            "Imputaciones": "3",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "3",
            "TotalCambate": "2%",
            "Archivos": "3",
            "NoAcciónPenal": "3",
            "Abstenciones": "8",
            "TotalNoCombate": "4%",
            "Presupuesto": "$3,648,442.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Durango",
            "Denuncias": "265",
            "Investigaciones": "0",
            "Carpetas": "265",
            "Imputaciones": "43",
            "Vinculaciones": "21",
            "Sentencias": "0",
            "Judicialización": "20",
            "Criterio": "0",
            "Controversias": "3",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "9%",
            "Archivos": "0",
            "NoAcciónPenal": "9",
            "Abstenciones": "3",
            "TotalNoCombate": "5%",
            "Presupuesto": "$24,409,097.00",
            "Montos": "$867,934.48 "
        },
        {
            "Entidad": "Federal",
            "Denuncias": "2166",
            "Investigaciones": "0",
            "Carpetas": "2463",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "64",
            "Criterio": "1",
            "Controversias": "28",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "4%",
            "Archivos": "0",
            "NoAcciónPenal": "281",
            "Abstenciones": "114",
            "TotalNoCombate": "16%",
            "Presupuesto": "$123,531,300.00",
            "Montos": "NR"
        },
        {
            "Entidad": "Guanajuato",
            "Denuncias": "51",
            "Investigaciones": "51",
            "Carpetas": "51",
            "Imputaciones": "6",
            "Vinculaciones": "4",
            "Sentencias": "1",
            "Judicialización": "6",
            "Criterio": "0",
            "Controversias": "8",
            "Suspensiónes": "2",
            "Procedimiento": "1",
            "Reparaciónes": "1",
            "TotalCambate": "35%",
            "Archivos": "1",
            "NoAcciónPenal": "34",
            "Abstenciones": "0",
            "TotalNoCombate": "69%",
            "Presupuesto": "$13,292,802.52 ",
            "Montos": "$1,748,326.00"
        },
        {
            "Entidad": "Guerrero",
            "Denuncias": "8",
            "Investigaciones": "8",
            "Carpetas": "8",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "0",
            "NoAcciónPenal": "4",
            "Abstenciones": "0",
            "TotalNoCombate": "50%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Hidalgo",
            "Denuncias": "414",
            "Investigaciones": "414",
            "Carpetas": "218",
            "Imputaciones": "5",
            "Vinculaciones": "14",
            "Sentencias": "5",
            "Judicialización": "1",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "6",
            "Procedimiento": "3",
            "Reparaciónes": "NR",
            "TotalCambate": "5%",
            "Archivos": "1",
            "NoAcciónPenal": "52",
            "Abstenciones": "NR",
            "TotalNoCombate": "24%",
            "Presupuesto": "$9,753,952.00",
            "Montos": "$985,687,060.90"
        },
        {
            "Entidad": "Jalisco",
            "Denuncias": "743",
            "Investigaciones": "NR",
            "Carpetas": "743",
            "Imputaciones": "15",
            "Vinculaciones": "15",
            "Sentencias": "2",
            "Judicialización": "62",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "9",
            "Procedimiento": "2",
            "Reparaciónes": "11",
            "TotalCambate": "11%",
            "Archivos": "51",
            "NoAcciónPenal": "1",
            "Abstenciones": "313",
            "TotalNoCombate": "49%",
            "Presupuesto": "$60,916,049.00",
            "Montos": "$-"
        },
        {
            "Entidad": "México",
            "Denuncias": "4342",
            "Investigaciones": "4284",
            "Carpetas": "4342",
            "Imputaciones": "7",
            "Vinculaciones": "83",
            "Sentencias": "25",
            "Judicialización": "194",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "27",
            "Procedimiento": "8",
            "Reparaciónes": "1",
            "TotalCambate": "5%",
            "Archivos": "590",
            "NoAcciónPenal": "3",
            "Abstenciones": "114",
            "TotalNoCombate": "16%",
            "Presupuesto": "$277,331,502.60",
            "Montos": "NR"
        },
        {
            "Entidad": "Michoacán",
            "Denuncias": "105",
            "Investigaciones": "105",
            "Carpetas": "105",
            "Imputaciones": "NR",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "19",
            "Criterio": "0",
            "Controversias": "8",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "26%",
            "Archivos": "15",
            "NoAcciónPenal": "40",
            "Abstenciones": "1",
            "TotalNoCombate": "53%",
            "Presupuesto": "$8,708,386.00",
            "Montos": "$15,443.00"
        },
        {
            "Entidad": "Morelos",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "194",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nayarit",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nuevo León",
            "Denuncias": "101",
            "Investigaciones": "3",
            "Carpetas": "2620",
            "Imputaciones": "33",
            "Vinculaciones": "18",
            "Sentencias": "2",
            "Judicialización": "45",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "7",
            "Procedimiento": "1",
            "Reparaciónes": "0",
            "TotalCambate": "2%",
            "Archivos": "927",
            "NoAcciónPenal": "17",
            "Abstenciones": "19",
            "TotalNoCombate": "37%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Oaxaca",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Puebla",
            "Denuncias": "569",
            "Investigaciones": "50",
            "Carpetas": "1142",
            "Imputaciones": "38",
            "Vinculaciones": "36",
            "Sentencias": "4",
            "Judicialización": "41",
            "Criterio": "0",
            "Controversias": "7",
            "Suspensiónes": "7",
            "Procedimiento": "1",
            "Reparaciónes": "3",
            "TotalCambate": "5%",
            "Archivos": "7",
            "NoAcciónPenal": "348",
            "Abstenciones": "0",
            "TotalNoCombate": "31%",
            "Presupuesto": "$29,131,466.82 ",
            "Montos": "$-"
        },
        {
            "Entidad": "Querétaro",
            "Denuncias": "50",
            "Investigaciones": "NR",
            "Carpetas": "50",
            "Imputaciones": "14",
            "Vinculaciones": "18",
            "Sentencias": "15",
            "Judicialización": "14",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "6",
            "Procedimiento": "15",
            "Reparaciónes": "1",
            "TotalCambate": "72%",
            "Archivos": "0",
            "NoAcciónPenal": "15",
            "Abstenciones": "3",
            "TotalNoCombate": "36%",
            "Presupuesto": "$18,539,365.86 ",
            "Montos": "$1,000,000.00"
        },
        {
            "Entidad": "Quintana Roo",
            "Denuncias": "425",
            "Investigaciones": "12",
            "Carpetas": "425",
            "Imputaciones": "47",
            "Vinculaciones": "43",
            "Sentencias": "3",
            "Judicialización": "55",
            "Criterio": "119",
            "Controversias": "0",
            "Suspensiónes": "19",
            "Procedimiento": "1",
            "Reparaciónes": "1",
            "TotalCambate": "46%",
            "Archivos": "0",
            "NoAcciónPenal": "170",
            "Abstenciones": "0",
            "TotalNoCombate": "40%",
            "Presupuesto": "$44,502,135.00",
            "Montos": "$1,664,924,645.48 "
        },
        {
            "Entidad": "San Luis Potosí",
            "Denuncias": "184",
            "Investigaciones": "0",
            "Carpetas": "184",
            "Imputaciones": "16",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "11",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "7%",
            "Archivos": "0",
            "NoAcciónPenal": "34",
            "Abstenciones": "2",
            "TotalNoCombate": "20%",
            "Presupuesto": "$5,071,058.42 ",
            "Montos": "$-"
        },
        {
            "Entidad": "Sinaloa",
            "Denuncias": "11",
            "Investigaciones": "1",
            "Carpetas": "13",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "1",
            "Reparaciónes": "1",
            "TotalCambate": "23%",
            "Archivos": "0",
            "NoAcciónPenal": "15",
            "Abstenciones": "10",
            "TotalNoCombate": "192%",
            "Presupuesto": "NR",
            "Montos": "$2,000,000.00"
        },
        {
            "Entidad": "Sonora",
            "Denuncias": "172",
            "Investigaciones": "0",
            "Carpetas": "169",
            "Imputaciones": "14",
            "Vinculaciones": "14",
            "Sentencias": "3",
            "Judicialización": "7",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "5%",
            "Archivos": "1",
            "NoAcciónPenal": "37",
            "Abstenciones": "11",
            "TotalNoCombate": "29%",
            "Presupuesto": "$56,765,156.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Tabasco",
            "Denuncias": "47",
            "Investigaciones": "0",
            "Carpetas": "47",
            "Imputaciones": "9",
            "Vinculaciones": "5",
            "Sentencias": "0",
            "Judicialización": "5",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "15%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "2",
            "TotalNoCombate": "4%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Tamaulipas",
            "Denuncias": "190",
            "Investigaciones": "0",
            "Carpetas": "190",
            "Imputaciones": "5",
            "Vinculaciones": "5",
            "Sentencias": "0",
            "Judicialización": "6",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "3%",
            "Archivos": "1",
            "NoAcciónPenal": "15",
            "Abstenciones": "12",
            "TotalNoCombate": "15%",
            "Presupuesto": "$5,979,640.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Tlaxcala",
            "Denuncias": "390",
            "Investigaciones": "386",
            "Carpetas": "386",
            "Imputaciones": "31",
            "Vinculaciones": "19",
            "Sentencias": "75",
            "Judicialización": "74",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "5",
            "TotalCambate": "22%",
            "Archivos": "4",
            "NoAcciónPenal": "7",
            "Abstenciones": "8",
            "TotalNoCombate": "5%",
            "Presupuesto": "$10,466,939.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Veracruz",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Yucatán",
            "Denuncias": "83",
            "Investigaciones": "0",
            "Carpetas": "60",
            "Imputaciones": "6",
            "Vinculaciones": "26",
            "Sentencias": "0",
            "Judicialización": "5",
            "Criterio": "1",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "2",
            "TotalCambate": "13%",
            "Archivos": "14",
            "NoAcciónPenal": "33",
            "Abstenciones": "0",
            "TotalNoCombate": "78%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Zacatecas",
            "Denuncias": "351",
            "Investigaciones": "0",
            "Carpetas": "351",
            "Imputaciones": "25",
            "Vinculaciones": "17",
            "Sentencias": "4",
            "Judicialización": "25",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "1",
            "Reparaciónes": "2",
            "TotalCambate": "9%",
            "Archivos": "65",
            "NoAcciónPenal": "1",
            "Abstenciones": "43",
            "TotalNoCombate": "31%",
            "Presupuesto": "$9,144,388.00",
            "Montos": "$-"
        }
    ],
    "2022": [
        {
            "Entidad": "Aguascalientes",
            "Denuncias": "53",
            "Investigaciones": "1",
            "Carpetas": "53",
            "Imputaciones": "2",
            "Vinculaciones": "2",
            "Sentencias": "0",
            "Judicialización": "1",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "1",
            "TotalCambate": "4%",
            "Archivos": "0",
            "NoAcciónPenal": "3",
            "Abstenciones": "0",
            "TotalNoCombate": "6%",
            "Presupuesto": "$8,481,600.00",
            "Montos": "$314,242.50"
        },
        {
            "Entidad": "Baja California",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Baja California Sur",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Campeche",
            "Denuncias": "245",
            "Investigaciones": "0",
            "Carpetas": "255",
            "Imputaciones": "14",
            "Vinculaciones": "11",
            "Sentencias": "1",
            "Judicialización": "21",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "4",
            "TotalCambate": "12%",
            "Archivos": "57",
            "NoAcciónPenal": "5",
            "Abstenciones": "7",
            "TotalNoCombate": "27%",
            "Presupuesto": "$11,312,659.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Chiapas",
            "Denuncias": "77",
            "Investigaciones": "5",
            "Carpetas": "77",
            "Imputaciones": "12",
            "Vinculaciones": "10",
            "Sentencias": "9",
            "Judicialización": "12",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "4",
            "Reparaciónes": "0",
            "TotalCambate": "23%",
            "Archivos": "0",
            "NoAcciónPenal": "25",
            "Abstenciones": "0",
            "TotalNoCombate": "32%",
            "Presupuesto": "$11,737,853.64 ",
            "Montos": "NR"
        },
        {
            "Entidad": "Chihuahua",
            "Denuncias": "20",
            "Investigaciones": "0",
            "Carpetas": "20",
            "Imputaciones": "6",
            "Vinculaciones": "6",
            "Sentencias": "1",
            "Judicialización": "6",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "1",
            "Reparaciónes": "1",
            "TotalCambate": "50%",
            "Archivos": "0",
            "NoAcciónPenal": "6",
            "Abstenciones": "0",
            "TotalNoCombate": "30%",
            "Presupuesto": "$62,512,466.00",
            "Montos": "$2,828,556.08 "
        },
        {
            "Entidad": "Ciudad de México",
            "Denuncias": "440",
            "Investigaciones": "NR",
            "Carpetas": "440",
            "Imputaciones": "31",
            "Vinculaciones": "21",
            "Sentencias": "NR",
            "Judicialización": "31",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "9",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "9%",
            "Archivos": "66",
            "NoAcciónPenal": "319",
            "Abstenciones": "0",
            "TotalNoCombate": "88%",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Coahuila",
            "Denuncias": "170",
            "Investigaciones": "170",
            "Carpetas": "170",
            "Imputaciones": "16",
            "Vinculaciones": "16",
            "Sentencias": "1",
            "Judicialización": "16",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "1",
            "Procedimiento": "1",
            "Reparaciónes": "0",
            "TotalCambate": "11%",
            "Archivos": "0",
            "NoAcciónPenal": "36",
            "Abstenciones": "0",
            "TotalNoCombate": "21%",
            "Presupuesto": "$28,222,873.56 ",
            "Montos": "$3,085,822.00"
        },
        {
            "Entidad": "Colima",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Durango",
            "Denuncias": "238",
            "Investigaciones": "2",
            "Carpetas": "216",
            "Imputaciones": "18",
            "Vinculaciones": "12",
            "Sentencias": "2",
            "Judicialización": "109",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "51%",
            "Archivos": "6",
            "NoAcciónPenal": "76",
            "Abstenciones": "7",
            "TotalNoCombate": "41%",
            "Presupuesto": "$28,886,746.00",
            "Montos": "$120,000.00"
        },
        {
            "Entidad": "Federal",
            "Denuncias": "908",
            "Investigaciones": "0",
            "Carpetas": "768",
            "Imputaciones": "38",
            "Vinculaciones": "35",
            "Sentencias": "3",
            "Judicialización": "64",
            "Criterio": "1",
            "Controversias": "9",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "10%",
            "Archivos": "0",
            "NoAcciónPenal": "187",
            "Abstenciones": "24",
            "TotalNoCombate": "27%",
            "Presupuesto": "$174,792,336.00",
            "Montos": "NR"
        },
        {
            "Entidad": "Guanajuato",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "68",
            "Imputaciones": "8",
            "Vinculaciones": "8",
            "Sentencias": "1",
            "Judicialización": "11",
            "Criterio": "NR",
            "Controversias": "13",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "35%",
            "Archivos": "3",
            "NoAcciónPenal": "44",
            "Abstenciones": "NR",
            "TotalNoCombate": "69%",
            "Presupuesto": "$13,229,411.04 ",
            "Montos": "$1,098,278.58 "
        },
        {
            "Entidad": "Guerrero",
            "Denuncias": "17",
            "Investigaciones": "17",
            "Carpetas": "17",
            "Imputaciones": "0",
            "Vinculaciones": "0",
            "Sentencias": "0",
            "Judicialización": "0",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "0%",
            "Archivos": "1",
            "NoAcciónPenal": "1",
            "Abstenciones": "0",
            "TotalNoCombate": "12%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Hidalgo",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Jalisco",
            "Denuncias": "766",
            "Investigaciones": "52",
            "Carpetas": "766",
            "Imputaciones": "64",
            "Vinculaciones": "54",
            "Sentencias": "1",
            "Judicialización": "48",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "7%",
            "Archivos": "55",
            "NoAcciónPenal": "0",
            "Abstenciones": "286",
            "TotalNoCombate": "45%",
            "Presupuesto": "$64,626,021.96 ",
            "Montos": "$1,076,071.40"
        },
        {
            "Entidad": "México",
            "Denuncias": "4513",
            "Investigaciones": "NR",
            "Carpetas": "4513",
            "Imputaciones": "NR",
            "Vinculaciones": "55",
            "Sentencias": "NR",
            "Judicialización": "31",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "9",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "66",
            "NoAcciónPenal": "319",
            "Abstenciones": "0",
            "TotalNoCombate": "9%",
            "Presupuesto": "$241,668,378.86 ",
            "Montos": "NR"
        },
        {
            "Entidad": "Michoacán",
            "Denuncias": "106",
            "Investigaciones": "3",
            "Carpetas": "106",
            "Imputaciones": "0",
            "Vinculaciones": "3",
            "Sentencias": "0",
            "Judicialización": "9",
            "Criterio": "0",
            "Controversias": "2",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "10%",
            "Archivos": "23",
            "NoAcciónPenal": "68",
            "Abstenciones": "12",
            "TotalNoCombate": "97%",
            "Presupuesto": "$9,475,885.00",
            "Montos": "$2,149,923.97 "
        },
        {
            "Entidad": "Morelos",
            "Denuncias": "599",
            "Investigaciones": "5",
            "Carpetas": "599",
            "Imputaciones": "30",
            "Vinculaciones": "10",
            "Sentencias": "1",
            "Judicialización": "35",
            "Criterio": "15",
            "Controversias": "0",
            "Suspensiónes": "10",
            "Procedimiento": "5",
            "Reparaciónes": "30",
            "TotalCambate": "16%",
            "Archivos": "30",
            "NoAcciónPenal": "10",
            "Abstenciones": "5",
            "TotalNoCombate": "8%",
            "Presupuesto": "$36,928,984.40",
            "Montos": "$-"
        },
        {
            "Entidad": "Nayarit",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Nuevo León",
            "Denuncias": "161",
            "Investigaciones": "3",
            "Carpetas": "1381",
            "Imputaciones": "71",
            "Vinculaciones": "36",
            "Sentencias": "2",
            "Judicialización": "71",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "6",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "6%",
            "Archivos": "461",
            "NoAcciónPenal": "4",
            "Abstenciones": "56",
            "TotalNoCombate": "38%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Oaxaca",
            "Denuncias": "866",
            "Investigaciones": "866",
            "Carpetas": "866",
            "Imputaciones": "16",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "11",
            "Criterio": "0",
            "Controversias": "13",
            "Suspensiónes": "1",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "3%",
            "Archivos": "44",
            "NoAcciónPenal": "32",
            "Abstenciones": "9",
            "TotalNoCombate": "10%",
            "Presupuesto": "$19,774,731.60",
            "Montos": "$-"
        },
        {
            "Entidad": "Puebla",
            "Denuncias": "1460",
            "Investigaciones": "1460",
            "Carpetas": "1323",
            "Imputaciones": "88",
            "Vinculaciones": "88",
            "Sentencias": "3",
            "Judicialización": "76",
            "Criterio": "0",
            "Controversias": "28",
            "Suspensiónes": "20",
            "Procedimiento": "1",
            "Reparaciónes": "11",
            "TotalCambate": "10%",
            "Archivos": "9",
            "NoAcciónPenal": "700",
            "Abstenciones": "1",
            "TotalNoCombate": "54%",
            "Presupuesto": "$53,952,079.25 ",
            "Montos": "$20,568.00"
        },
        {
            "Entidad": "Querétaro",
            "Denuncias": "286",
            "Investigaciones": "0",
            "Carpetas": "286",
            "Imputaciones": "17",
            "Vinculaciones": "32",
            "Sentencias": "11",
            "Judicialización": "17",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "9",
            "Procedimiento": "6",
            "Reparaciónes": "3",
            "TotalCambate": "12%",
            "Archivos": "0",
            "NoAcciónPenal": "52",
            "Abstenciones": "12",
            "TotalNoCombate": "22%",
            "Presupuesto": "$20,005,784.56 ",
            "Montos": "$3,261,223.07 "
        },
        {
            "Entidad": "Quintana Roo",
            "Denuncias": "359",
            "Investigaciones": "44",
            "Carpetas": "359",
            "Imputaciones": "39",
            "Vinculaciones": "31",
            "Sentencias": "0",
            "Judicialización": "43",
            "Criterio": "208",
            "Controversias": "NR",
            "Suspensiónes": "4",
            "Procedimiento": "0",
            "Reparaciónes": "NR",
            "TotalCambate": "71%",
            "Archivos": "0",
            "NoAcciónPenal": "247",
            "Abstenciones": "0",
            "TotalNoCombate": "69%",
            "Presupuesto": "$49,060,974.00",
            "Montos": "$163,078,161.73 "
        },
        {
            "Entidad": "San Luis Potosí",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Sinaloa",
            "Denuncias": "19",
            "Investigaciones": "0",
            "Carpetas": "16",
            "Imputaciones": "7",
            "Vinculaciones": "7",
            "Sentencias": "0",
            "Judicialización": "3",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "19%",
            "Archivos": "0",
            "NoAcciónPenal": "3",
            "Abstenciones": "1",
            "TotalNoCombate": "25%",
            "Presupuesto": "NR",
            "Montos": "$-"
        },
        {
            "Entidad": "Sonora",
            "Denuncias": "390",
            "Investigaciones": "0",
            "Carpetas": "390",
            "Imputaciones": "53",
            "Vinculaciones": "52",
            "Sentencias": "0",
            "Judicialización": "38",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "5",
            "Procedimiento": "6",
            "Reparaciónes": "NR",
            "TotalCambate": "13%",
            "Archivos": "2",
            "NoAcciónPenal": "30",
            "Abstenciones": "2",
            "TotalNoCombate": "9%",
            "Presupuesto": "$63,556,554.00",
            "Montos": "$4,762,580.76 "
        },
        {
            "Entidad": "Tabasco",
            "Denuncias": "77",
            "Investigaciones": "NR",
            "Carpetas": "77",
            "Imputaciones": "11",
            "Vinculaciones": "11",
            "Sentencias": "1",
            "Judicialización": "7",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "9%",
            "Archivos": "0",
            "NoAcciónPenal": "0",
            "Abstenciones": "0",
            "TotalNoCombate": "0%",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Tamaulipas",
            "Denuncias": "176",
            "Investigaciones": "176",
            "Carpetas": "176",
            "Imputaciones": "11",
            "Vinculaciones": "10",
            "Sentencias": "1",
            "Judicialización": "13",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "2",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "9%",
            "Archivos": "5",
            "NoAcciónPenal": "62",
            "Abstenciones": "16",
            "TotalNoCombate": "47%",
            "Presupuesto": "$7,970,823.00",
            "Montos": "NR"
        },
        {
            "Entidad": "Tlaxcala",
            "Denuncias": "NR",
            "Investigaciones": "NR",
            "Carpetas": "NR",
            "Imputaciones": "NR",
            "Vinculaciones": "NR",
            "Sentencias": "NR",
            "Judicialización": "NR",
            "Criterio": "NR",
            "Controversias": "NR",
            "Suspensiónes": "NR",
            "Procedimiento": "NR",
            "Reparaciónes": "NR",
            "TotalCambate": "NR",
            "Archivos": "NR",
            "NoAcciónPenal": "NR",
            "Abstenciones": "NR",
            "TotalNoCombate": "NR",
            "Presupuesto": "NR",
            "Montos": "NR"
        },
        {
            "Entidad": "Veracruz",
            "Denuncias": "925",
            "Investigaciones": "842",
            "Carpetas": "925",
            "Imputaciones": "8",
            "Vinculaciones": "1",
            "Sentencias": "0",
            "Judicialización": "8",
            "Criterio": "0",
            "Controversias": "AR",
            "Suspensiónes": "0",
            "Procedimiento": "0",
            "Reparaciónes": "0",
            "TotalCambate": "1%",
            "Archivos": "0",
            "NoAcciónPenal": "45",
            "Abstenciones": "33",
            "TotalNoCombate": "8%",
            "Presupuesto": "$5,581,282.00",
            "Montos": "$-"
        },
        {
            "Entidad": "Yucatán",
            "Denuncias": "70",
            "Investigaciones": "3",
            "Carpetas": "39",
            "Imputaciones": "9",
            "Vinculaciones": "8",
            "Sentencias": "1",
            "Judicialización": "9",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "4",
            "Procedimiento": "1",
            "Reparaciónes": "0",
            "TotalCambate": "36%",
            "Archivos": "15",
            "NoAcciónPenal": "26",
            "Abstenciones": "17",
            "TotalNoCombate": "149%",
            "Presupuesto": "$19,777,095.00",
            "Montos": "$189,166.66 "
        },
        {
            "Entidad": "Zacatecas",
            "Denuncias": "451",
            "Investigaciones": "0",
            "Carpetas": "451",
            "Imputaciones": "7",
            "Vinculaciones": "4",
            "Sentencias": "2",
            "Judicialización": "15",
            "Criterio": "0",
            "Controversias": "0",
            "Suspensiónes": "11",
            "Procedimiento": "3",
            "Reparaciónes": "1",
            "TotalCambate": "7%",
            "Archivos": "181",
            "NoAcciónPenal": "0",
            "Abstenciones": "150",
            "TotalNoCombate": "73%",
            "Presupuesto": "$9,269,551.81 ",
            "Montos": "$1,746,000.00"
        }
    ]
}
